In [2]:
import pandas as pd
import numpy as np

In [10]:
df=pd.DataFrame(np.arange(1,21).reshape(5,4),index=['Rone','Rtwo','Rthree','Rfour','Rfive'],columns=['Col1','Col2','Col3','Col4'])

In [12]:
df.head()

Col1  Col2  Col3  Col4
Rone       1     2     3     4
Rtwo       5     6     7     8
Rthree     9    10    11    12
Rfour     13    14    15    16
Rfive     17    18    19    20

In [14]:
df.to_csv('DataFrame Example')

In [20]:
#Accessing elements
#1. .Loc 2. .iloc
df.loc['Rone']

Col1    1
Col2    2
Col3    3
Col4    4
Name: Rone, dtype: int32

In [22]:
df.loc['Rfive']

Col1    17
Col2    18
Col3    19
Col4    20
Name: Rfive, dtype: int32

In [24]:
type(df.loc['Rone'])

pandas.core.series.Series

In [28]:
df.iloc[0:2,0:2]

Col1  Col2
Rone     1     2
Rtwo     5     6

In [30]:
df.iloc[0:4,0:3]

Col1  Col2  Col3
Rone       1     2     3
Rtwo       5     6     7
Rthree     9    10    11
Rfour     13    14    15

In [32]:
df.iloc[3:,1:]

Col2  Col3  Col4
Rfour    14    15    16
Rfive    18    19    20

In [34]:
type(df.iloc[3:,1:])

pandas.core.frame.DataFrame

In [42]:
#into an array
df.iloc[:,1:].values

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [44]:
df.iloc[:,:].values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [48]:
df['Col2'].value_counts()

Col2
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [50]:
df['Col2'].unique()

array([ 2,  6, 10, 14, 18])

In [52]:
df['Col4']

Rone       4
Rtwo       8
Rthree    12
Rfour     16
Rfive     20
Name: Col4, dtype: int32