In [1]:
import numpy as np

In [91]:
my_list=[1,3,5,7,9,10,11,12,13,14,15]
my_array=np.array(my_list)

In [5]:
my_array

array([1, 3, 5, 7, 9])

In [7]:
type(my_array)

numpy.ndarray

In [9]:
my_array.shape

(5,)

In [11]:
#2d array
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]
two_d=np.array([l1,l2,l3])

In [13]:
two_d

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
two_d.shape

(3, 5)

In [17]:
two_d.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

# INDEXING

In [ ]:
#11 12 13 14 15
 0 1 2 3 4 5
-5 -4 -3 -2 -1

In [ ]:
one_arr=np.array([2,4,6,8,10])

In [37]:
import numpy as np  # Ensure numpy is imported

In [39]:

one_arr = np.array([2, 4, 6, 8, 10])

In [41]:
one_arr

array([ 2,  4,  6,  8, 10])

In [43]:
one_arr[4]

10

In [51]:
#2d array
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]
two_d=np.array([l1,l2,l3])

In [53]:
two_d

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [55]:
two_d[:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [57]:
two_d[0:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [59]:
two_d[1:,3:]

array([[5, 6],
       [6, 7]])

In [61]:
two_d[2:,1:]

array([[4, 5, 6, 7]])

In [69]:
inbuilt1=np.arange(1,25)

In [71]:
inbuilt1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [73]:
inbuilt1=np.arange(1,25,3)

In [75]:
inbuilt1

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [79]:
inbuilt1=np.arange(1,30,4)

In [81]:
inbuilt1

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [89]:
np.linspace(1,40,15)

array([ 1.        ,  3.78571429,  6.57142857,  9.35714286, 12.14285714,
       14.92857143, 17.71428571, 20.5       , 23.28571429, 26.07142857,
       28.85714286, 31.64285714, 34.42857143, 37.21428571, 40.        ])

In [ ]:
#copy fun

In [105]:
copy_func=np.array([1,3,5,7,9,10,11,12,13,14,15])

In [107]:
copy_func

array([ 1,  3,  5,  7,  9, 10, 11, 12, 13, 14, 15])

In [109]:
copy_func1=copy_func

In [111]:
copy_func1[3:]=300

In [113]:
print(copy_func1)

[  1   3   5 300 300 300 300 300 300 300 300]


In [119]:
copy_func[3:]=150

In [121]:
print(copy_func)

[  1   3   5 150 150 150 150 150 150 150 150]


In [123]:
copy_func1=copy_func.copy()


In [125]:
print(copy_func)
copy_func1[3:]=300
print(copy_func1)

[  1   3   5 150 150 150 150 150 150 150 150]
[  1   3   5 300 300 300 300 300 300 300 300]


In [127]:
print(copy_func1)

[  1   3   5 300 300 300 300 300 300 300 300]


In [129]:
var=5
copy_func1<var

array([ True,  True, False, False, False, False, False, False, False,
       False, False])

In [131]:
copy_func1[copy_func1>var]

array([300, 300, 300, 300, 300, 300, 300, 300])

In [133]:
np.ones(4)

array([1., 1., 1., 1.])

In [93]:
my_array

array([ 1,  3,  5,  7,  9, 10, 11, 12, 13, 14, 15])

In [95]:
my_array1=my_array

In [97]:
my_array1[3:]=400

In [99]:
print(my_array1)

[  1   3   5 400 400 400 400 400 400 400 400]


In [101]:
my_array1[:3]=100

In [103]:
print(my_array1)

[100 100 100 400 400 400 400 400 400 400 400]
